# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

script:
  - "python -m unittest logging_tree.tests.test_format logging_tree.tests.test_node"
